[package]
name = "benchpress"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.36", features = ["derive"] }
colored = "3.0.0"
reqwest = "0.12.15"
tokio = { version = "1.44.2", features = ["full"] }
url = "2.5.4"
